import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const packageJsonPath = join(__dirname, '../package.json');
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));

// Generate version.js file
const versionPath = join(__dirname, '../src/version.js');
const versionContent = `// This file is auto-generated by scripts/update-version.js
// DO NOT EDIT MANUALLY

export const version = '${packageJson.version}';
export const name = '${packageJson.name}';
export const description = '${packageJson.description}';
export const author = '${packageJson.author}';
export const license = '${packageJson.license}';

export default {
  version,
  name,
  description,
  author,
  license
};
`;

writeFileSync(versionPath, versionContent, 'utf8');
console.log(`Generated src/version.js with version ${packageJson.version}`);