name: Dependency Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run security audit
        run: |
          npm audit --production
          npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Check for outdated dependencies
        run: npm outdated || true
      
      - name: Create issue for vulnerabilities
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const date = new Date().toISOString().split('T')[0];
            const title = `Security vulnerabilities detected - ${date}`;
            
            // Check if issue already exists
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['security', 'dependencies']
            });
            
            const existingIssue = issues.find(issue => issue.title.includes('Security vulnerabilities detected'));
            
            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: `Security vulnerabilities were detected in the dependencies.\n\n` +
                      `Please run \`npm audit\` locally to see the details and fix them.\n\n` +
                      `This issue was automatically created by the dependency check workflow.`,
                labels: ['security', 'dependencies', 'automated']
              });
            }